POST http://localhost:3000/posts
Content-Type: application/json
{
  "title": "My New Post Title 2",
  "slug": "my-new-post-title-2",
  "content": "This is content 2",
  "status": "draft",
    "tag" : [{"label":"san kyi tar par 2","description":"min ga lar par 2"}],
  "meta": {
    "readTime": "10 mins " 
  }
}