GET http://localhost:3000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwiaWF0IjoxNzgzMzE0NzQ4LCJleHAiOjE3ODMzMTgzNDgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.OvOlfd6FLCafQHi1ZK7mkcP_8s6OGMTGS8NIkCC_pTg


GET http://localhost:3000/posts?limit=3

GET http://localhost:3000/posts?limit=3&page=3