POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "min thein khaing",
  "lastName": "khaing",
  "email": "mintheinkhaing0@gmail.com",
  "password": "SecurePass12d#"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json

{
  "users": [
    {
      "firstName": "Mike",
      "lastName": "Doed",
      "email": "johd@gmail.com",
      "password": "SecurePass123#"
    },
    {
      "firstName": "Johns ssd",
      "lastName": "Doea",
      "email": "john.doeeeddafd@gmail.com",
      "password": "SecurePass123#"
    }
  ]
}
