POST http://localhost:3000/auth/sign-in
Content-Type: application/json
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwiaWF0IjoxNzgyMjgzMzEyLCJleHAiOjE3ODIyODY5MTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.xs31RbvRVNW7V-Gb7DP7ocAkaYELpIqmY08UXJXRLYc

{
  "email": "admin@email.com",
  "password": "SecurePass12d#"
}
